### ISSUE TITLE
Installer does not install database

### ISSUE THREAD

**Issue by ukd1** [ushahidi/Swiftriver-2011#39]
Installer does not install database (Batuque)

**Comment by jgosier** [comment]
that sounds like an issue with your db as we've installed it on several machines just fine.  Still, can you tell us more about what happened and your environment?

**Comment by jgosier** [comment]
Also, the DB tables are all dynamically generated at the moment (for dev reasons) so you wouldn't see any tables post install, until you start using the app.

**Comment by ukd1** [comment]
The installer finished, and nothing was created. I've used the app, and nothing was created - no errors either.

I'm running Debian Lenny, PHP 5.3, lighttpd & 5.0.67 mysql (or newer 5.0.x).

Dev reasons?

**Comment by jgosier** [comment]
Hrmm, are you using Chrome perhaps?

**Comment by ukd1** [comment]
Yes, Chromium?

**Comment by jgosier** [comment]
Try it in Firefox.  From the release notes and README:  "Supports IE7+, FireFox, Safari"

We're well aware that it shipped not working in Chrome, it's a javascript issue.

**Comment by ukd1** [comment]
If I get time to re-install it I will, but at the moment it's low on things to do. I uninstalled it after it just didn't work.

**Comment by jgosier** [comment]
Sounds good, the Alpha is for hardcore developers or people simply looking test or offer ideas.  It's a public alpha because we like getting feedback as we work.  That said, expecting it to 'just work' isn't what they are there for, as they're iterative and not final. Thanks for the feedback, though.  I suggest you take a look in August if you've still got an interest or play with the demo at http://swift.ushahidi.com/rc

**Comment by ukd1** [comment]
Yeah - unfortunately I don't have time at the moment :-(
