### ISSUE TITLE
Passwords need to be salted before saving

### ISSUE THREAD

**Issue by tmcw** [ushahidi/Swiftriver-2011#52]
Right now, RiverID simply runs `$password = md5($password);`. This makes the RiverID system extremely susceptible to dictionary attacks: [a password salt](http://www.aspheute.com/english/20040105.asp) should be used.

**Comment by mrmatthewgriffiths** [comment]
Hi tmcw,

Yer we are aware of this vulnerability. The RiverID system is far from the finished article and should really have been shipped with an alpha style notice.

Once again, thanks for your interest in our software.

Matt

**Comment by tmcw** [comment]
This raises the question of why RiverID isn't a layer on top of OpenID, or why it's included at the alpha level. People are certainly going to install this software, and it doesn't make much sense to write authentication systems from scratch when many good solutions exist. (Also, keeping awareness of the fact that adding password salts in, for instance, an upgrade script, is impossible without reassigning all user passwords)

**Comment by jgosier** [comment]
@TMCW You're thinking like we are.  I'm not sure which code you're looking at.  The login system is just in place temporarily (we have a fulltime staff of 1), so it takes time).  RiverID actually is being written on top of OpenID and Oauth standards, that's the whole point.  

If you've got some spare time we could use help that area just because our staff is small, and thus we have to prioritize features.
